### ISSUE TITLE
Sponsors section on homepage is not positioned correctly

### ISSUE THREAD

**Issue by fdatoo** [SpongePowered/SpongeHome#79] opened 2016-05-06 19:49 UTC
![screenshot](http://i.imgur.com/e3CJJo3.jpg)

**The problem:** The sponsors section on the homepage is positioned below the masthead text.
**Expected behavior:** The sponsors section should be to the right of the masthead text.

**Comment by jamierocks** [comment] 2016-05-06 19:54
Duplicate of https://github.com/SpongePowered/SpongeHome/issues/68 ;)

I have been investigating this issue, problem is however Apple make nothing easy and like opening a Mac up in 2016 developer tools are none-existent :P

**Closed as completed** 2016-05-06 20:00 UTC
