### ISSUE TITLE
Looks weird on 4:3

### ISSUE THREAD

**Issue by benazarenko** [SpongePowered/SpongeHome#80] opened 2016-05-06 20:09 UTC
I use safari 9.1 on my mac mini with 4:3 monitor (1280x1024). And this page looks weird on this screen resolution.
http://i.imgur.com/6W8MHv5.jpg

**Comment by stephan-gh** [comment] 2016-05-06 20:21
Working fine on Firefox with the same resolution

**Comment by Tzky** [comment] 2016-05-06 20:24
It should be related to Safari. Using other browsers seems fine. This is possibly a duplicate of #68, so closing for now

**Closed as completed by Tzky** 2016-05-06 20:24 UTC

**Comment by benazarenko** [comment] 2016-05-06 20:27
I tried to use fix from #68 and it finally looks good.

> #main-display {
>   padding-top: 15%;
>   display: table;
>   padding: 1em 1em 2em;
>   width: 74%
>   img { float: left; }
>   img, .intro-text {
>     display: table-cell;
>     vertical-align: middle;
>   }
> }
